# How do delays relate to traffic volume and airport performances? 

We need to analyze first:
- Delay rate (calculate from df_AID): total delays/total flights per airport per month
- Traffic volume: total flights 
And then deep dive into aiport performances:  
- Efficiencies: consistency coefficient (from Q2), taxi in & out efficiency (TOTAL_REF_TIME_MIN + TOTAL_ADD_TIME_MIN)/VALID_FL, Departure Punctuality %, Arrival Punctuality %

In [6]:
#Importing all libraries needed
import pandas as pd
import plotly.express as px
import ipywidgets as widgets
from IPython.display import display

In [7]:
#Datasets used
df_AID= pd.read_excel("datasets/Airport_IATA_delays_airline_reported.xlsx")
df_AT = pd.read_excel("datasets/AirportTraffic.xlsx")
df_AP = pd.read_excel("datasets/Airports_Punctuality.xlsx")

In [8]:
# AIRPORT TRAFFIC DATAFRAME per year per airport
df_TRA_top20 = (
    df_AT
    .groupby(["YEAR", "APT_ICAO"], observed=True)[["FLT_TOT_1", "FLT_DEP_1", "FLT_ARR_1"]]
    .sum()
    .reset_index()
    .merge(
        df_AT[["APT_ICAO", "APT_NAME", "STATE_NAME"]].drop_duplicates("APT_ICAO"),
        on="APT_ICAO",
        how="left"
    )
)
# Sort by year and flights
df_TRA_top20 = df_TRA_top20.sort_values(["YEAR", "FLT_TOT_1"], ascending=[True, False])
# Keep only the top 20 airports per year
df_TRA_top20 = (
    df_TRA_top20.groupby("YEAR", group_keys=False)
    .head(20)
    .reset_index(drop=True)
    .rename(columns={
        "FLT_TOT_1": "Total Flights",}
    )
)
airports_code_list = df_TRA_top20["APT_ICAO"].unique().tolist()

display(df_TRA_top20.head(40))

,YEAR,APT_ICAO,Total Flights,FLT_DEP_1,FLT_ARR_1,APT_NAME,STATE_NAME
0,2023,LTFM,502051,251000,251051,Istanbul,Türkiye
1,2023,EHAM,458183,229095,229088,Amsterdam - Schiphol,Netherlands
2,2023,EGLL,456739,228318,228421,London - Heathrow,United Kingdom
3,2023,LFPG,455146,227589,227557,Paris-Charles-de-Gaulle,France
4,2023,EDDF,430389,215168,215221,Frankfurt,Germany
5,2023,LEMD,389214,194611,194603,Madrid - Barajas,Spain
6,2023,LEBL,318977,159483,159494,Barcelona,Spain
7,2023,EDDM,299771,149880,149891,Munich,Germany
8,2023,LIRF,266510,133250,133260,Rome - Fiumicino,Italy
9,2023,EGKK,256936,128461,128475,London - Gatwick,United Kingdom
10,2023,LSZH,243029,121494,121535,Zürich,Switzerland
11,2023,EIDW,240694,120342,120352,Dublin,Ireland
12,2023,LGAV,236540,118250,118290,Athens,Greece
13,2023,LOWW,235281,117611,117670,Vienna,Austria
14,2023,LEPA,227838,113913,113925,Palma de Mallorca,Spain
15,2023,EKCH,227333,113628,113705,Copenhagen - Kastrup,Denmark
16,2023,LPPT,226762,113397,113365,Lisbon,Portugal
17,2023,LTFJ,220872,110416,110456,Istanbul Sabiha Gökçen,Türkiye
18,2023,LTAI,218995,109457,109538,Antalya,Türkiye
19,2023,ENGM,215993,108003,107990,Oslo - Gardermoen,Norway
20,2024,LTFM,512818,256380,256438,Istanbul,Türkiye
21,2024,EHAM,489071,244562,244509,Amsterdam - Schiphol,Netherlands
22,2024,EGLL,476359,238155,238204,London - Heathrow,United Kingdom
23,2024,LFPG,466770,233408,233362,Paris-Charles-de-Gaulle,France
24,2024,EDDF,440830,220397,220433,Frankfurt,Germany
25,2024,LEMD,420321,210133,210188,Madrid - Barajas,Spain
26,2024,LEBL,347992,173982,174010,Barcelona,Spain
27,2024,EDDM,324545,162261,162284,Munich,Germany
28,2024,LIRF,315648,157818,157830,Rome - Fiumicino,Italy
29,2024,EGKK,265395,132685,132710,London - Gatwick,United Kingdom
30,2024,LGAV,264066,131946,132120,Athens,Greece
31,2024,LSZH,258199,129063,129136,Zürich,Switzerland
32,2024,LOWW,248103,124019,124084,Vienna,Austria
33,2024,EIDW,243836,121910,121926,Dublin,Ireland
34,2024,LEPA,241929,120962,120967,Palma de Mallorca,Spain
35,2024,EKCH,240676,120318,120358,Copenhagen - Kastrup,Denmark
36,2024,LTFJ,233720,116826,116894,Istanbul Sabiha Gökçen,Türkiye
37,2024,LPPT,229194,114614,114580,Lisbon,Portugal
38,2024,LTAI,228292,114153,114139,Antalya,Türkiye
39,2024,ENGM,219493,109742,109751,Oslo - Gardermoen,Norway

Let's find the delay rate as the ratio between total delayed flights and total flights, for each of the 20 airports, in every month between 2023 and 2024

In [9]:

# AIRPORT IATA DELAY DATAFRAME per year per airport
# Filter the delay dataset for only the top 20 airports
df_AID_TOP20 = df_AID[df_AID["APT_ICAO"].isin(airports_code_list)].copy()
# Calculate delay ratio as percentage
df_AID_TOP20["Delay_Ratio"] = (df_AID_TOP20["TF"] / df_AID_TOP20["Total_Flights_Period"]) * 100
# Provide key insights per year per airport
df_AID_TOP20_YA = (
    df_AID_TOP20
    .groupby(["Year_Lobt","APT_ICAO"], as_index=False)
    .agg({
        "TD": "sum",
        "TF": "sum",
        "adm": "sum",
        "pd": "mean",
        "Delay_Ratio": "mean" 
    })
    .sort_values(by="TF", ascending=False)
    .rename(columns={
        "Year_Lobt": "YEAR",
        "TD": "Total Delay (TD)",
        "TF": "Total Flights Affected",
        "adm": "Avg Delay per Movement (in min)",
        "pd": "Avg Proportion of Delay (%)",
        "Delay_Rate": "Avg Delay Ratio (%)"
    })
    .reset_index(drop=True)
    .sort_values(["APT_ICAO"], ascending=[True])
)
display(df_AID_TOP20_YA)

,YEAR,APT_ICAO,Total Delay (TD),Total Flights Affected,Avg Delay per Movement (in min),Avg Proportion of Delay (%),Delay_Ratio
0,2024,EDDF,2279095,226394,178.763985,4.516793,8.695810
1,2023,EDDF,2360075,212753,190.674794,4.421168,8.412021
5,2024,EDDM,1436489,137042,145.805902,3.959321,6.897277
9,2023,EDDM,1215142,111430,132.717408,3.923711,5.946353
17,2024,EGKK,1202460,74676,139.395739,3.360100,4.340599
16,2023,EGKK,1262695,75089,152.232961,3.206110,4.567035
30,2023,EGLL,587483,42081,121.558077,3.501350,4.294067
31,2024,EGLL,509045,40469,111.164903,2.918641,4.354144
3,2023,EHAM,1998459,159733,141.533813,3.950663,5.581137
2,2024,EHAM,2153278,182475,136.094625,3.881811,5.666039
22,2023,EIDW,988227,63598,127.911577,3.406540,4.070044
26,2024,EIDW,818089,55066,105.809392,3.520792,3.501190
33,2024,EKCH,436303,34564,54.968848,2.722353,2.141038
32,2023,EKCH,514101,39340,72.403540,2.508770,2.749209
34,2023,ENGM,393598,32393,55.668457,2.889895,2.207860
36,2024,ENGM,401084,31299,54.678485,2.984540,2.069659
21,2023,LEBL,937638,66520,94.736058,3.224857,3.294115
14,2024,LEBL,1118856,78959,95.515673,3.100616,3.334680
27,2023,LEMD,742706,54782,101.879703,3.369276,3.692815
24,2024,LEMD,888111,62620,105.606178,3.504568,3.673501
29,2023,LEPA,750827,50487,102.116763,2.723215,3.528264
25,2024,LEPA,956013,60272,111.601877,2.799015,3.726470
7,2023,LFPG,2906784,127678,209.435248,4.778683,4.533268
6,2024,LFPG,2732214,129753,190.358226,4.795028,4.448700
28,2023,LGAV,734091,53132,111.753098,3.539079,4.175230
23,2024,LGAV,869178,62932,119.317279,3.708085,4.468514
19,2023,LIRF,1053658,70872,125.400284,3.334715,4.237661
13,2024,LIRF,1268369,83319,129.125613,3.310087,4.343006
18,2023,LOWW,755801,73027,93.637083,3.462195,4.485195
15,2024,LOWW,893984,78793,102.674389,3.418745,4.590114
11,2024,LPPT,1369445,91840,180.864031,3.898839,5.948629
10,2023,LPPT,1570334,97341,200.306443,3.943985,6.116664
12,2024,LSZH,928353,88989,127.362208,3.663748,6.046202
20,2023,LSZH,739849,69340,120.304203,3.585548,5.512213
35,2024,LTAI,481922,31491,120.974705,3.552098,4.099590
37,2023,LTAI,419945,29780,124.025380,3.053900,4.495712
38,2023,LTFJ,398843,27952,131.937013,4.038091,4.480110
39,2024,LTFJ,338574,22583,141.244842,4.676447,4.581040
8,2024,LTFM,2031172,115980,125.462223,4.656713,3.542436
4,2023,LTFM,1989825,141779,128.411149,3.860450,4.469682

In [10]:
# SETUP Dataframes for merging AID and AT datasets
df_merged_AID_AT = (
    df_AID_TOP20_YA.merge(
        df_TRA_top20[["YEAR", "APT_ICAO", "Total Flights", "APT_NAME", "STATE_NAME"]],
        on=["YEAR", "APT_ICAO"],
        how="inner" 
    )
    .sort_values(["YEAR", "Total Flights"], ascending=[True, False])
    .reset_index(drop=True)
)
display(df_merged_AID_AT.head(40))

,YEAR,APT_ICAO,Total Delay (TD),Total Flights Affected,Avg Delay per Movement (in min),Avg Proportion of Delay (%),Delay_Ratio,Total Flights,APT_NAME,STATE_NAME
0,2023,LTFM,1989825,141779,128.411149,3.860450,4.469682,502051,Istanbul,Türkiye
1,2023,EHAM,1998459,159733,141.533813,3.950663,5.581137,458183,Amsterdam - Schiphol,Netherlands
2,2023,EGLL,587483,42081,121.558077,3.501350,4.294067,456739,London - Heathrow,United Kingdom
3,2023,LFPG,2906784,127678,209.435248,4.778683,4.533268,455146,Paris-Charles-de-Gaulle,France
4,2023,EDDF,2360075,212753,190.674794,4.421168,8.412021,430389,Frankfurt,Germany
5,2023,LEMD,742706,54782,101.879703,3.369276,3.692815,389214,Madrid - Barajas,Spain
6,2023,LEBL,937638,66520,94.736058,3.224857,3.294115,318977,Barcelona,Spain
7,2023,EDDM,1215142,111430,132.717408,3.923711,5.946353,299771,Munich,Germany
8,2023,LIRF,1053658,70872,125.400284,3.334715,4.237661,266510,Rome - Fiumicino,Italy
9,2023,EGKK,1262695,75089,152.232961,3.206110,4.567035,256936,London - Gatwick,United Kingdom
10,2023,LSZH,739849,69340,120.304203,3.585548,5.512213,243029,Zürich,Switzerland
11,2023,EIDW,988227,63598,127.911577,3.406540,4.070044,240694,Dublin,Ireland
12,2023,LGAV,734091,53132,111.753098,3.539079,4.175230,236540,Athens,Greece
13,2023,LOWW,755801,73027,93.637083,3.462195,4.485195,235281,Vienna,Austria
14,2023,LEPA,750827,50487,102.116763,2.723215,3.528264,227838,Palma de Mallorca,Spain
15,2023,EKCH,514101,39340,72.403540,2.508770,2.749209,227333,Copenhagen - Kastrup,Denmark
16,2023,LPPT,1570334,97341,200.306443,3.943985,6.116664,226762,Lisbon,Portugal
17,2023,LTFJ,398843,27952,131.937013,4.038091,4.480110,220872,Istanbul Sabiha Gökçen,Türkiye
18,2023,LTAI,419945,29780,124.025380,3.053900,4.495712,218995,Antalya,Türkiye
19,2023,ENGM,393598,32393,55.668457,2.889895,2.207860,215993,Oslo - Gardermoen,Norway
20,2024,LTFM,2031172,115980,125.462223,4.656713,3.542436,512818,Istanbul,Türkiye
21,2024,EHAM,2153278,182475,136.094625,3.881811,5.666039,489071,Amsterdam - Schiphol,Netherlands
22,2024,EGLL,509045,40469,111.164903,2.918641,4.354144,476359,London - Heathrow,United Kingdom
23,2024,LFPG,2732214,129753,190.358226,4.795028,4.448700,466770,Paris-Charles-de-Gaulle,France
24,2024,EDDF,2279095,226394,178.763985,4.516793,8.695810,440830,Frankfurt,Germany
25,2024,LEMD,888111,62620,105.606178,3.504568,3.673501,420321,Madrid - Barajas,Spain
26,2024,LEBL,1118856,78959,95.515673,3.100616,3.334680,347992,Barcelona,Spain
27,2024,EDDM,1436489,137042,145.805902,3.959321,6.897277,324545,Munich,Germany
28,2024,LIRF,1268369,83319,129.125613,3.310087,4.343006,315648,Rome - Fiumicino,Italy
29,2024,EGKK,1202460,74676,139.395739,3.360100,4.340599,265395,London - Gatwick,United Kingdom
30,2024,LGAV,869178,62932,119.317279,3.708085,4.468514,264066,Athens,Greece
31,2024,LSZH,928353,88989,127.362208,3.663748,6.046202,258199,Zürich,Switzerland
32,2024,LOWW,893984,78793,102.674389,3.418745,4.590114,248103,Vienna,Austria
33,2024,EIDW,818089,55066,105.809392,3.520792,3.501190,243836,Dublin,Ireland
34,2024,LEPA,956013,60272,111.601877,2.799015,3.726470,241929,Palma de Mallorca,Spain
35,2024,EKCH,436303,34564,54.968848,2.722353,2.141038,240676,Copenhagen - Kastrup,Denmark
36,2024,LTFJ,338574,22583,141.244842,4.676447,4.581040,233720,Istanbul Sabiha Gökçen,Türkiye
37,2024,LPPT,1369445,91840,180.864031,3.898839,5.948629,229194,Lisbon,Portugal
38,2024,LTAI,481922,31491,120.974705,3.552098,4.099590,228292,Antalya,Türkiye
39,2024,ENGM,401084,31299,54.678485,2.984540,2.069659,219493,Oslo - Gardermoen,Norway

In [11]:
# Scatter plot 
def plot_year_scatter(df, year):
    dff = (
        df.loc[df["YEAR"] == year, 
               ["APT_ICAO", "YEAR", "Total Flights", "Total Delay (TD)", "APT_NAME", "STATE_NAME"]]
          .dropna(subset=["Total Flights", "Total Delay (TD)"])
    )
    title = f"Total Flights vs Total Delay — {year} (Top 20 Airports)"
    fig = px.scatter(
        dff,
        x="Total Flights",
        y="Total Delay (TD)",
        text="APT_ICAO",
        size="Total Flights",
        color="Total Delay (TD)",
        hover_data=["APT_NAME", "STATE_NAME", "Total Flights", "Total Delay (TD)"],
        labels={"Total Flights": "Total Flights (per year)",
                "Total Delay (TD)": "Total Delay (minutes)"},
        title=title,
    )
    fig.update_traces(textposition="top center")
    fig.update_layout(
        template="plotly_white",
        hovermode="closest",
        xaxis_title="Total Flights",
        yaxis_title="Total Delay (minutes)",
        legend_title="Total Delay (minutes)"
    )
    fig.show()
# --- Plots ---
plot_year_scatter(df_merged_AID_AT, 2023)
plot_year_scatter(df_merged_AID_AT, 2024)