# How do delays relate to traffic volume and airport performances? 

We need to analyze first:
- Delay rate (calculate from df_AID): total delays/total flights per airport per month
- Traffic volume: total flights 
And then deep dive into aiport performances:  
- Efficiencies: consistency coefficient (from Q2), taxi in & out efficiency (TOTAL_REF_TIME_MIN + TOTAL_ADD_TIME_MIN)/VALID_FL, Departure Punctuality %, Arrival Punctuality %

In [1]:
#Importing all libraries needed
import pandas as pd
import plotly.express as px
import ipywidgets as widgets
from IPython.display import display

In [2]:
#Datasets used
df_AID= pd.read_excel("datasets/Airport_IATA_delays_airline_reported.xlsx")
df_AT = pd.read_excel("datasets/AirportTraffic.xlsx")
df_TIn = pd.read_excel("datasets/Taxi-In_Additional_Time.xlsx")
df_TOut = pd.read_excel("datasets/Taxi-Out_Additional_Time.xlsx")
df_AP = pd.read_excel("datasets/Airports_Punctuality.xlsx")

In [3]:
df_top20 = (
    df_AT.groupby("APT_ICAO")[["FLT_TOT_1", "FLT_DEP_1", "FLT_ARR_1"]] #Group by airport code
    .sum().sort_values(by="FLT_TOT_1",ascending=False) #Sum the values for each code of the 3 columns indicated
    .head(20).reset_index()) #Change "20" to change the number of airports analysed

# Adding airport's city name and state from original dataset
df_top20 = (df_top20.merge(df_AT[["APT_ICAO", "APT_NAME", "STATE_NAME"]]
                           .drop_duplicates(), on="APT_ICAO", how="left"))
airports_code_list = df_top20["APT_ICAO"].tolist()

Let's find the delay rate as the ratio between total delayed flights and total flights, for each of the 20 airports, in every month between 2023 and 2024

In [4]:
# Filter the delay dataset for only the top 20 airports
df_AID_TOP20 = df_AID[df_AID["APT_ICAO"].isin(airports_code_list)].copy()

# Calculate delay ratio as percentage
df_AID_TOP20["Delay_Ratio"] = (df_AID_TOP20["TF"] / df_AID_TOP20["Total_Flights_Period"]) * 100

# Provide key insights per year per month per airport
df_AID_TOP20_YMA = (
    df_AID_TOP20
    .groupby(["Year_Lobt","Month_Lobt","APT_ICAO"], as_index=False)
    .agg({
        "TD": "sum",
        "TF": "sum",
        "Total_Flights_Period": "sum",
        "adm": "mean",
        "pd": "mean",
        "Delay_Ratio": "mean" 
    })
    .sort_values(by="TF", ascending=False)
    .rename(columns={
        "TD": "Total Delay (TD)",
        "TF": "Total Flights (TF)",
        "Total_Flights_Period": "Total_Flights_Period",
        "adm": "Avg Delay per Movement (in min)",
        "pd": "Avg Proportion of Delay (%)",
        "Delay_Rate": "Avg Delay Ratio (%)"
    })
    .reset_index(drop=True)
    .sort_values(["APT_ICAO", "Year_Lobt"])
)
display(df_AID_TOP20_YMA)

,Year_Lobt,Month_Lobt,APT_ICAO,Total Delay (TD),Total Flights (TF),Total_Flights_Period,Avg Delay per Movement (in min),Avg Proportion of Delay (%),Delay_Ratio
3,2023,August,EDDF,291567,21990,240295,1.213371,4.496111,9.151252
4,2023,July,EDDF,246893,21909,237439,1.039817,4.288736,9.227212
6,2023,October,EDDF,222135,20932,246228,0.902152,4.392308,8.501064
7,2023,June,EDDF,236981,20731,234583,1.010222,4.493097,8.837384
8,2023,September,EDDF,208035,20193,216257,0.961980,4.366834,9.337501
...,...,...,...,...,...,...,...,...,...
160,2024,May,LTFM,105376,7982,279463,0.377066,4.998136,2.856192
171,2024,November,LTFM,124082,7454,252824,0.490784,4.559046,2.948296
172,2024,April,LTFM,125240,7423,269620,0.464506,5.041028,2.753134
212,2024,March,LTFM,85614,6571,256190,0.334182,4.803897,2.564893
218,2024,February,LTFM,76954,6416,238510,0.322645,4.812624,2.690034

This dataframe contains both the delay rate (Delay_Ratio) and the total flights (Total_Flights_Period).
For the performances we consider:
- consistency coefficient (from Q2) 
- taxi in & out efficiency (TOTAL_REF_TIME_MIN + TOTAL_ADD_TIME_MIN)/VALID_FL
- Departure and Arrival Punctuality %

In [5]:
'''Consistency coefficient code missing'''

'Consistency coefficient code missing'

Taxis efficiencies: import and cleaning datasets

In [6]:
df_TIn = pd.read_excel("datasets/Taxi-In_Additional_Time.xlsx")
df_TOut = pd.read_excel("datasets/Taxi-Out_Additional_Time.xlsx")

In [7]:
df_taxi_time_in = (
    df_TIn[(df_TIn["APT_ICAO"].isin(airports_code_list)) & 
           ((df_TIn["YEAR"] == 2023) | (df_TIn["YEAR"] == 2024))]
    .groupby(["APT_ICAO", "YEAR"])[["VALID_FL", "TOTAL_REF_NB_FL", "TOTAL_REF_TIME_MIN", "TOTAL_ADD_TIME_MIN"]]
    .sum()
    .reset_index()
)
#In order: filter only airports in top 20, filter only values from 2023-24, group by code and sum the values in the 
#listed columns, reset the index to have the codes as a column itselft (useful for merging)

df_airport_codes = pd.DataFrame({'APT_ICAO': airports_code_list})
# Merging taxi with airport codes
df_taxi_time_in = pd.merge(df_airport_codes, df_taxi_time_in, on='APT_ICAO', how='left')
df_taxi_time_in["TI_EFF"] = (df_taxi_time_in["TOTAL_REF_TIME_MIN"] + df_taxi_time_in["TOTAL_ADD_TIME_MIN"])/df_taxi_time_in["VALID_FL"] #Minutes per flight
df_taxi_time_in.head()

,APT_ICAO,YEAR,VALID_FL,TOTAL_REF_NB_FL,TOTAL_REF_TIME_MIN,TOTAL_ADD_TIME_MIN,TI_EFF
0,LTFM,2023.0,252135.0,224348.0,2.373240e+06,855390.200000,12.805164
1,LTFM,2024.0,257977.0,241852.0,2.765769e+06,714479.700000,13.490540
2,EHAM,2023.0,229015.0,205963.0,1.382420e+06,454441.723333,8.020704
3,EHAM,2024.0,244901.0,219269.0,1.556295e+06,474765.903333,8.293394
4,EGLL,2023.0,227395.0,222931.0,1.220305e+06,905222.600000,9.347294

In [8]:
df_taxi_time_out = (
    df_TOut[(df_TOut["APT_ICAO"].isin(airports_code_list)) & 
           ((df_TOut["YEAR"] == 2023) | (df_TOut["YEAR"] == 2024))]
    .groupby(["APT_ICAO", "YEAR"])[["VALID_FL", "TOTAL_REF_NB_FL", "TOTAL_REF_TIME_MIN", "TOTAL_ADD_TIME_MIN"]]
    .sum()
    .reset_index()
)

# Merging taxi in with taxi out
df_taxi_time_out = pd.merge(df_airport_codes, df_taxi_time_out, on='APT_ICAO', how='left').dropna()
df_taxi_time_out["TO_EFF"] = (df_taxi_time_out["TOTAL_ADD_TIME_MIN"] + df_taxi_time_out["TOTAL_REF_TIME_MIN"])/df_taxi_time_out["VALID_FL"] #Minutes per flight
df_taxi_time_out.head()

,APT_ICAO,YEAR,VALID_FL,TOTAL_REF_NB_FL,TOTAL_REF_TIME_MIN,TOTAL_ADD_TIME_MIN,TO_EFF
0,LTFM,2023.0,249480.0,229117.0,2.666089e+06,1.212654e+06,15.547310
1,LTFM,2024.0,257483.0,243220.0,2.932272e+06,1.193205e+06,16.022328
2,EHAM,2023.0,227592.0,210298.0,1.889884e+06,6.709732e+05,11.251963
3,EHAM,2024.0,244951.0,218970.0,2.047181e+06,7.474638e+05,11.408995
4,EGLL,2023.0,227616.0,223922.0,3.365869e+06,1.601565e+06,21.823747

Merging the datasets and removing unnecessary columns

In [9]:
df_tt_efficiencies = pd.merge(df_taxi_time_out, df_taxi_time_in, on=["APT_ICAO", "YEAR"], how="left")
tt_cols_todrop = ["VALID_FL_x", "TOTAL_REF_NB_FL_x", "TOTAL_REF_TIME_MIN_x", "TOTAL_ADD_TIME_MIN_x", "VALID_FL_y", "TOTAL_REF_NB_FL_y", "TOTAL_REF_TIME_MIN_y", "TOTAL_ADD_TIME_MIN_y"]
df_tt_efficiencies = df_tt_efficiencies.drop(columns=tt_cols_todrop, axis=1)
df_tt_efficiencies.head()

  APT_ICAO    YEAR     TO_EFF     TI_EFF
0     LTFM  2023.0  15.547310  12.805164
1     LTFM  2024.0  16.022328  13.490540
2     EHAM  2023.0  11.251963   8.020704
3     EHAM  2024.0  11.408995   8.293394
4     EGLL  2023.0  21.823747   9.347294

Depart & Arrival Punctualities

In [10]:
airport_map = {
    "LTFM": "Istanbul",
    "EHAM": "Amsterdam",
    "EGLL": "London Heathrow",
    "LFPG": "Paris Charles de Gaulle",
    "EDDF": "Frankfurt",
    "LEMD": "Madrid Barajas",
    "LEBL": "Barcelona",
    "EDDM": "Munich",
    "LIRF": "Rome Fiumicino",
    "EGKK": "London Gatwick",
    "LSZH": "Zurich",
    "LGAV": "Athens",
    "EIDW": "Dublin",
    "LOWW": "Vienna",
    "LEPA": "Palma de Mallorca",
    "EKCH": "Copenhagen",
    "LPPT": "Lisbon",
    "LTFJ": "Istanbul Sabiha Gokcen",
    "LTAI": "Antalya",
    "ENGM": "Oslo"
} #Dataset has different names from the ones used before

In [11]:
top20_codes = [airport_map[a] for a in df_top20['APT_ICAO'] if a in airport_map]
df_AP_top20 = df_AP[df_AP['Airport'].isin(top20_codes)]

name_to_icao = {name: icao for icao, name in airport_map.items()}
icao_codes = df_AP_top20["Airport"].map(name_to_icao)
df_AP_top20.insert(loc=2, column="APT_ICAO", value=df_AP_top20["Airport"].map(name_to_icao))

df_AP_top20.head()

,Date,Airport,APT_ICAO,Departure Punctuality %,Arrival Punctuality %,Avg Departure Schedule Delay,Avg Arrival Schedule Delay,Avg Departure - Arrival Schedule Delay,Operated Schedules %
1367,2022-01-01,Frankfurt,EDDF,0.818898,0.804217,13.043920,13.426908,-0.382988,0.922170
1368,2022-01-02,Frankfurt,EDDF,0.707216,0.713389,17.652062,18.506590,-0.854528,0.946463
1369,2022-01-03,Frankfurt,EDDF,0.738938,0.755991,16.235140,13.956209,2.278931,0.952183
1370,2022-01-04,Frankfurt,EDDF,0.630542,0.725962,16.605624,14.621955,1.983669,0.953811
1371,2022-01-05,Frankfurt,EDDF,0.782816,0.821951,10.382379,9.699187,0.683192,0.946785

Adding the month and year column from the date one

In [12]:
df_AP_top20["Year"] = df_AP_top20["Date"].dt.year.astype(str)
df_AP_top20["Month"] = df_AP_top20["Date"].dt.month.apply(lambda x: f'{x:02d}')

C:\Users\vermeej\AppData\Local\Temp\ipykernel_8824\578300410.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_AP_top20["Year"] = df_AP_top20["Date"].dt.year.astype(str)
C:\Users\vermeej\AppData\Local\Temp\ipykernel_8824\578300410.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_AP_top20["Month"] = df_AP_top20["Date"].dt.month.apply(lambda x: f'{x:02d}')

Filtering the dataset and dropping unnecessary columns

In [13]:
AP_cols_todrop = ["Avg Departure Schedule Delay", "Avg Arrival Schedule Delay", "Avg Departure - Arrival Schedule Delay", "Operated Schedules %"]
df_AP_efficiencies = (df_AP_top20[df_AP_top20["Date"].dt.year.astype(str).isin(["2023", "2024"])]
                      .groupby(["APT_ICAO", "Year", "Month"])
                      .mean(["Departure Punctuality %", "Arrival Punctuality %"])
                      .reset_index()).drop(columns=AP_cols_todrop, axis=1)
df_AP_efficiencies

    APT_ICAO  Year Month  Departure Punctuality %  Arrival Punctuality %
0       EDDF  2023    01                 0.667677               0.784448
1       EDDF  2023    02                 0.636383               0.766183
2       EDDF  2023    03                 0.532972               0.701877
3       EDDF  2023    04                 0.659708               0.754957
4       EDDF  2023    05                 0.589679               0.602905
..       ...   ...   ...                      ...                    ...
475     LTFM  2024    08                 0.636076               0.671603
476     LTFM  2024    09                 0.680400               0.713811
477     LTFM  2024    10                 0.778200               0.783877
478     LTFM  2024    11                 0.821263               0.825065
479     LTFM  2024    12                 0.803159               0.789897

[480 rows x 5 columns]

Now that we have some efficiencies:
- plot in the same chart the delay rate, traffic flow, effieciency trends through the years and see if there are some patterns