In [1]:
import pandas as pd
import geopandas as gpd
from dash import Dash, dcc, html, Input, Output
import plotly.express as px

In [2]:
## collecting all of the neccesary data
df_Ageo_top20 = pd.read_csv("datasets_rq4/df_Ageo_top20.csv")
df_AT_top20_month = pd.read_csv("datasets_rq4/df_AT_top20_month.csv")
# df_rq1m = pd.read_csv("datasets_rq4/.....")
# df_rq1t = pd.read_csv("datasets_rq4/.....")
# df_rq2m = pd.read_csv("datasets_rq4/.....")
# df_rq2t = pd.read_csv("datasets_rq4/.....")
world = gpd.read_file("https://naciscdn.org/naturalearth/110m/cultural/ne_110m_admin_0_countries.zip")
print(df_AT_top20_month.head(1))
df_Ageo_top20.head(1)

   Unnamed: 0 APT_ICAO  YEAR  MONTH_NUM    FLT_MEAN  FLT_MEAN_DEP  \
0           0     EDDF  2023          1  958.419355    479.967742

   FLT_MEAN_ARR
0    478.451613

,Unnamed: 0,ident,name,latitude_deg,longitude_deg,elevation_ft
0,0,EDDF,Frankfurt am Main Airport,50.033333,8.570556,364.0

Merging all datasets to one

In [13]:
df_AT_top20_month['month_year'] = df_AT_top20_month['YEAR'].astype(str) + '-' + df_AT_top20_month['MONTH_NUM'].astype(str).str.zfill(2)

df_total = pd.merge(df_AT_top20_month, df_Ageo_top20,
                    left_on='APT_ICAO', right_on='ident', how='left')
df_total

,Unnamed: 0_x,APT_ICAO,YEAR,MONTH_NUM,FLT_MEAN,FLT_MEAN_DEP,FLT_MEAN_ARR,month_year,Unnamed: 0_y,ident,name,latitude_deg,longitude_deg,elevation_ft
0,0,EDDF,2023,1,958.419355,479.967742,478.451613,2023-01,0,EDDF,Frankfurt am Main Airport,50.033333,8.570556,364.0
1,1,EDDF,2023,2,970.535714,485.357143,485.178571,2023-02,0,EDDF,Frankfurt am Main Airport,50.033333,8.570556,364.0
2,2,EDDF,2023,3,1036.129032,518.096774,518.032258,2023-03,0,EDDF,Frankfurt am Main Airport,50.033333,8.570556,364.0
3,3,EDDF,2023,4,1183.433333,591.333333,592.100000,2023-04,0,EDDF,Frankfurt am Main Airport,50.033333,8.570556,364.0
4,4,EDDF,2023,5,1202.193548,600.935484,601.258065,2023-05,0,EDDF,Frankfurt am Main Airport,50.033333,8.570556,364.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,475,LTFM,2024,8,1500.258065,750.290323,749.967742,2024-08,19,LTFM,Istanbul Airport,41.261297,28.741951,325.0
476,476,LTFM,2024,9,1480.800000,740.166667,740.633333,2024-09,19,LTFM,Istanbul Airport,41.261297,28.741951,325.0
477,477,LTFM,2024,10,1364.354839,682.290323,682.064516,2024-10,19,LTFM,Istanbul Airport,41.261297,28.741951,325.0
478,478,LTFM,2024,11,1339.166667,669.433333,669.733333,2024-11,19,LTFM,Istanbul Airport,41.261297,28.741951,325.0
479,479,LTFM,2024,12,1362.290323,680.677419,681.612903,2024-12,19,LTFM,Istanbul Airport,41.261297,28.741951,325.0

## Code for the map

In [19]:
map_fig = px.scatter_map(
    df_total,
    lat="latitude_deg",
    lon="longitude_deg",
    size="FLT_MEAN",
    # color="delay",
    hover_name="name",
    map_style="carto-positron",
    zoom=4,
    width=1000,
    height=700,
    animation_frame="month_year",
    size_max=35
)

map_fig.show()